/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ai-recipe-settings`; params?: Router.UnknownInputParams; } | { pathname: `/recipe-detail`; params?: Router.UnknownInputParams; } | { pathname: `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `/saved-recipes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/food-details` | `/food-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/type-ingredient` | `/type-ingredient`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pantry` | `/pantry`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ai-recipe-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/recipe-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/recipes`; params?: Router.UnknownOutputParams; } | { pathname: `/saved-recipes`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/food-details` | `/food-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/scan` | `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modals)'}/type-ingredient` | `/type-ingredient`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pantry` | `/pantry`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ai-recipe-settings${`?${string}` | `#${string}` | ''}` | `/recipe-detail${`?${string}` | `#${string}` | ''}` | `/recipes${`?${string}` | `#${string}` | ''}` | `/saved-recipes${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/food-details${`?${string}` | `#${string}` | ''}` | `/food-details${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/scan${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `${'/(modals)'}/type-ingredient${`?${string}` | `#${string}` | ''}` | `/type-ingredient${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pantry${`?${string}` | `#${string}` | ''}` | `/pantry${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ai-recipe-settings`; params?: Router.UnknownInputParams; } | { pathname: `/recipe-detail`; params?: Router.UnknownInputParams; } | { pathname: `/recipes`; params?: Router.UnknownInputParams; } | { pathname: `/saved-recipes`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/food-details` | `/food-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/scan` | `/scan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modals)'}/type-ingredient` | `/type-ingredient`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pantry` | `/pantry`; params?: Router.UnknownInputParams; };
    }
  }
}
